### ISSUE TITLE
Navbar elements are invisible

### ISSUE THREAD

**Issue by sanngridhr** [catppuccin/codeberg#8]
![Screenshot 2023-05-22 at 21-36-25 Codeberg org](https://github.com/catppuccin/codeberg/assets/63781175/c7d2508c-cf36-4c65-9be5-612edd5c57cc)

When they're hovered on, they're green

**Comment by justTOBBI** [comment]
Hey, sorry for the issues. I was working on completely rewriting the theme based on the gitea theme.
Due to my lack of time I can't really do it at the moment but I will surely add this to my watch-out-for list.
Could you maybe install the theme from the dev branch and see if that will maybe solve the issue?

**Comment by sanngridhr** [comment]
Everything works, thanks.

P. S. Sorry for the late answer, I reinstalled my system and had no time to test.
